repository:
    topics: website, golang, go-templates, ainsley-dev, webdev
    private: false
    allow_merge_commit: false
    delete_branch_on_merge: true
teams:
    -   name: core
        permission: admin
branches:
    -   name: main
        protection:
            required_pull_request_reviews: null
            required_status_checks: null
            enforce_admins: false
            allow_force_pushes: false
            allow_deletions: false
            restrictions:
                apps: [ ]
                users: [ ]
                teams:
                    - core
