// Code generated by mockery v2.33.3. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	slack "github.com/slack-go/slack"
)

// Sender is an autogenerated mock type for the Sender type
type Sender struct {
	mock.Mock
}

// Send provides a mock function with given fields: ctx, channelID, subject, fields
func (_m *Sender) Send(ctx context.Context, channelID string, subject string, fields []slack.AttachmentField) error {
	ret := _m.Called(ctx, channelID, subject, fields)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, []slack.AttachmentField) error); ok {
		r0 = rf(ctx, channelID, subject, fields)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewSender creates a new instance of Sender. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSender(t interface {
	mock.TestingT
	Cleanup(func())
}) *Sender {
	mock := &Sender{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
