navMain:
    -   identifier: bio
        name: Bio
        url: "/#bio"
        weight: 10
    -   identifier: media
        name: Media
        url: "/#media"
        weight: 20
    -   identifier: skills
        name: Skills
        url: "/#skills"
        weight: 30
    -   identifier: insights
        name: Insights
        url: /insights/
        weight: 40
    -   identifier: contact
        name: Say hello
        url: "/#contact"
        weight: 50
footer:
    -   identifier: bio
        name: Bio
        url: "/#bio"
        weight: 10
    -   identifier: media
        name: Media
        url: "/#media"
        weight: 20
    -   identifier: skills
        name: Skills
        url: "/#skills"
        weight: 30
    -   identifier: insights
        name: Insights
        url: /insights/
        weight: 40
    -   identifier: contact
        name: Say hello
        url: "/#contact"
        weight: 50
terms:
    -   identifier: terms-conditions
        name: Terms
        url: /terms/
        weight: 0
    -   identifier: privacy
        name: Privacy
        url: /privacy/
        weight: 10
    -   identifier: cookies
        name: Cookies
        url: /cookies/
        weight: 20
    -   identifier: guidelines
        name: Guidelines
        url: /guidelines/
        weight: 30
schema:
    -   identifier: home
        name: Home
        url: /
        weight: 10
    -   identifier: insights
        name: Insights
        url: /insights/
        weight: 20
    -   identifier: contact
        name: Say hello
        url: /contact/
        weight: 30
