name: Dispatch Guidelines Update

on:
    workflow_dispatch:
    push:
        branches:
            - main
        paths:
            - 'content/guidelines/**'

jobs:
    dispatch:
        name: Send repository dispatch event
        runs-on: ubuntu-latest
        permissions:
            contents: write
        steps:
            -   name: Create GitHub App token
                uses: actions/create-github-app-token@v2
                id: app-token
                with:
                    app-id: 2161597
                    private-key: ${{ secrets.ORG_GITHUB_APP_PRIVATE_KEY }}

            -   name: Repository Dispatch
                uses: peter-evans/repository-dispatch@v4
                with:
                    token: ${{ steps.app-token.outputs.token }}
                    repository: ainsleydev/webkit
                    event-type: guidelines-updated
                    client-payload: '{"ref":"main","sha":"${{ github.sha }}"}'
